apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: ezegrosfeld/expiration
          env:
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: EXPIRATION_REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: EXPIRATION_REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: EXPIRATION_REDIS_PASSWORD
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      dnsPolicy: Default
