apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
      - ./*/k8s/*
build:
  googleCloudBuild:
    projectId: ticketing-307923
  artifacts:
    - image: gcr.io/ticketing-307923/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .