apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
          - name: tickets
            image: gcr.io/ticketing-307923/tickets
            env:
              - name: JWT_KEY
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: JWT_KEY
              - name: MONGO_URI
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: TICKETS_URI
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000