name: deploy-orders
on:
  push:
    branches:
      - main
    paths:
      - orders/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && docker build -t ezegrosfeld/orders .
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ezegrosfeld --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ezegrosfeld/orders
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_KEY}}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment orders-depl
