name: deploy-manifests
on:
  push:
    branches:
      - main
    paths:
      - k8s/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: digitalocean/action-doctl@v2
       with:
        token: ${{ secrets.DO_KEY}}
     - run: doctl kubernetes cluster kubeconfig save ticketing
     - run: kubectl apply -f k8s && kubectl apply -f k8s/prod
